### ISSUE TITLE
Error in tensor_utils.batched_together when running sim_inference.py

### ISSUE THREAD

**Issue by dcbiton** [bjing2016/mdgen#1]
```
Traceback (most recent call last):
  File "/data/Dionessa/mdgen/sim_inference.py", line 140, in <module>
    main()
  File "/data/Dionessa/p312-str2str/lib/python3.12/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/data/Dionessa/mdgen/sim_inference.py", line 137, in main
    do(model, name, df.seqres[name])
  File "/data/Dionessa/mdgen/sim_inference.py", line 103, in do
    item = get_batch(name, seqres, num_frames = model.args.num_frames)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/Dionessa/mdgen/sim_inference.py", line 40, in get_batch
    atom37 = torch.from_numpy(atom14_to_atom37(arr, seqres[None])).float()
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/Dionessa/mdgen/mdgen/geometry.py", line 10, in atom14_to_atom37
    atom37 = batched_gather(
             ^^^^^^^^^^^^^^^
  File "/data/Dionessa/mdgen/mdgen/tensor_utils.py", line 92, in batched_gather
    return data[ranges]
           ~~~~^^^^^^^^
ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (4,) + inhomogeneous part.
```

**Comment by dcbiton** [comment]
Solved by changing ranges to tuple in newer version of pytorch 
in `mdgen.tensor_utils.batched_gather()` : 
`return data[tuple(ranges)]`

**Comment by lfs119** [comment]
![image](https://github.com/user-attachments/assets/90abb2c5-4e88-4a98-bd58-93bb80e10a4d)
  can you share your env with newer version of pytorch

**Comment by dcbiton** [comment]
Hi, I'm using `python3.12 `with `pytorch==2.4.1+cu121 `
But i think your error is different, which is on your input sizes. What is the size of your molecule ?

**Comment by lfs119** [comment]
Thanks.  I just follow the README.MD and run tps_inference.py

**Comment by lfs119** [comment]
“return data[tuple(ranges)] ”  is work on sim_inference but tps_inference is error. maybe some bugs in tps_inference.py
